<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrderFlow.Application\OrderFlow.Application.csproj" />
    <ProjectReference Include="..\OrderFlow.Domain\OrderFlow.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
    <Folder Include="ExternalServices\" />
    <Folder Include="Services\" />
    <Folder Include="Persistence\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
